name: Apply

on:
  push:
    branches: [main]
    paths:
      - "provision/kv/**"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: apply
  cancel-in-progress: false

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Apply
        uses: resumaestro/pit-boss/actions/apply@main
        with:
          provision_dir: provision/kv
          target: RESUMAESTRO_CONFIG
          proxy_url: ${{ vars.OBOIST_URL }}
          proxy_token: ${{ secrets.OBOIST_SECRET }}
